client: Dubai Police
project: SWAT Tactical Communication System
brand: beacon-red
version: v1.0
date: '2025-09-06'
title: Rough Order of Magnitude - SWAT Tactical Communication System
executive_summary: >-
  Complete tactical communication platform for Dubai Police SWAT operations. 10
  complete operator kits with INVISIO X7 headsets, V60 control units, Samsung
  Galaxy devices, and tactical mounting systems. DDP delivery terms.
objectives: >-
  Deploy professional-grade tactical communication equipment for 10 SWAT
  operators. Integrate INVISIO audio systems with Samsung Galaxy devices for
  ATAK. Provide complete chest-mounted tactical communication solution. Ensure
  39dB noise reduction capability for extreme environments.
deliverables: >-
  10x INVISIO X7 In-Ear Headset systems, 10x INVISIO V60 PTT Control Gen2 units,
  10x Samsung Galaxy devices, 10x Bunker Scout Battery systems, Complete chest
  mount systems with MIL-STD tactical mounting, 20x MIL-SPEC tactical cables
assumptions: >-
  Tetra radio systems will be provided by Dubai Police. ATAK software
  installation handled by Dubai Police. Site access and facility delivery
  coordination by client. Import permits and customs coordination by client.
bom_table: |-
  | Component | Quantity | Unit Price (AED) | Total (AED) |
  |-----------|----------|------------------|-------------|
  | INVISIO X7 In-Ear Headset | 10 | 8,900 | 89,000 |
  | INVISIO V60 PTT Control Gen2 | 10 | 8,069 | 80,690 |
  | Samsung Galaxy S23 Ultra | 10 | 7,344 | 73,440 |
  | Bunker Scout Battery | 10 | 775 | 7,750 |
  | Chest Mount System | 10 | 592 | 5,920 |
  | MAAK Phone Case | 10 | 2,585 | 25,850 |
  | MIL-SPEC Cables (2x) | 20 | 295 | 5,900 |
  | Integration Hardware | 10 | 1,480 | 14,800 |
  | **SUBTOTAL** | | | **303,350** |
  | Shipping & Handling | | | 15,168 |
  | Customs & Duties | | | 20,830 |
  | **TOTAL (S23 Ultra)** | | | **339,348** |
boq_table: |-
  | Item | Description | Unit | Quantity | Rate (AED) | Amount (AED) |
  |------|-------------|------|----------|------------|-------------|
  | 1.1 | INVISIO X7 In-Ear Headset | Each | 10 | 8,900 | 89,000 |
  | 1.2 | INVISIO V60 PTT Control Gen2 | Each | 10 | 8,069 | 80,690 |
  | 1.3 | Samsung Galaxy S23 Ultra 512GB | Each | 10 | 7,344 | 73,440 |
  | 1.4 | Bunker Scout Battery System | Each | 10 | 775 | 7,750 |
  | 1.5 | Tactical Chest Mount System | Each | 10 | 592 | 5,920 |
  | 1.6 | MAAK Phone Case MIL-STD-810H | Each | 10 | 2,585 | 25,850 |
  | 1.7 | MIL-SPEC Tactical Cable | Each | 20 | 295 | 5,900 |
  | 1.8 | Integration Hardware Kit | Each | 10 | 1,480 | 14,800 |
pricing_structure: >-
  Standard Configuration (S23 Ultra): AED 339,348 (10 kits), Upgraded
  Configuration (S25 Ultra): AED 341,228 (10 kits)
payment_terms: >-
  Terms to be negotiated based on procurement requirements. DDP pricing includes
  all shipping, customs, duties, and VAT. Delivery to Dubai Police facility
  included.
warranty_support: >-
  Manufacturer warranties on all INVISIO equipment. Samsung standard warranty on
  devices. Technical support for system integration. Documentation and training
  materials provided.
sla: >-
  Professional installation and commissioning services. Technical support for
  system integration. Training and documentation provided.
